services:

  postgres:
    image: postgres:18
    container_name: budgetmate-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql


  backend:
    build: ./backend
    container_name: budgetmate-backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: budgetmate-frontend
    ports:
      - "5174:80"
    depends_on:
      - backend

volumes:
  postgres_data:

