apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: budgetmate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kajol1288/budgetmate-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: budgetmate
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: kajol


---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: budgetmate
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
